[package]
name = "rgrep"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
regex = { version = "1.11" }
colored = "2"
anyhow = "1"
glob = "0.3"
itertools = "0.10"
rayon = "1"
thiserror = "1"
