[package]
name = "yamux_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.79"
futures = "0.3.30"
tokio = { version = "1.35.1", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
yamux = "0.13.1"

